### ISSUE TITLE
CT Registered PhetioObject baseline must equal baseline schema

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/diffusion#5]
Also in Gases Intro
```
diffusion : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/diffusion/diffusion_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/tandem/js/phetioAPIValidation.js:116:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/TinyEmitter.js:69:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:269:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:169:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:339:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/14/2020, 3:36:20 AM
diffusion : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/diffusion/diffusion_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/tandem/js/phetioAPIValidation.js:116:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/TinyEmitter.js:69:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:269:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:169:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:339:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/14/2020, 3:36:20 AM
diffusion : phet-io-mirror-inputs-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/phet-io-wrappers/mirror-inputs/?sim=diffusion&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/tandem/js/phetioAPIValidation.js:116:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/TinyEmitter.js:69:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:269:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:169:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:339:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/14/2020, 3:36:20 AM
diffusion : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/phet-io-wrappers/state/?sim=diffusion&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/tandem/js/phetioAPIValidation.js:116:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/TinyEmitter.js:69:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:269:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:169:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:339:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/14/2020, 3:36:20 AM
diffusion : phet-io-studio-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/studio/?sim=diffusion&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/tandem/js/phetioAPIValidation.js:116:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/TinyEmitter.js:69:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:269:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:169:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/axon/js/Property.js:339:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586856980100/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/14/2020, 3:36:20 AM
```

**Comment by pixelzoom** [comment]
Oops. I changed gas-properties iO API, and forgot to also update diffusion and gases-intro. Fixed in the above commits. Closing.
