### ISSUE TITLE
support ?shuffleListeners

### ISSUE THREAD

**Issue by zepumph** [phetsims/diffusion#7]
From phetsims/axon#215, when running with ?shuffleListeners, we get this error: assigning to responsible dev to determine if it is worth fixing:

```
diffusion
Uncaught Error: Assertion failed: particles1 has not been populated yet
Error: Assertion failed: particles1 has not been populated yet
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at DiffusionModel.numberOfParticlesProperty.DerivedProperty.numberType (http://localhost:8080/gas-properties/js/diffusion/model/DiffusionModel.js:108:21)
    at listener (http://localhost:8080/axon/js/DerivedProperty.js:73:35)
    at TinyEmitter.emit (http://localhost:8080/axon/js/TinyEmitter.js:69:53)
    at NumberProperty._notifyListeners (http://localhost:8080/axon/js/Property.js:273:25)
    at NumberProperty.set (http://localhost:8080/axon/js/Property.js:171:14)
    at http://localhost:8080/sun/js/NumberSpinner.js:166:28
    at TinyEmitter.emit (http://localhost:8080/axon/js/TinyEmitter.js:69:53)
    at http://localhost:8080/axon/js/Emitter.js:33:29
    at Emitter.execute (http://localhost:8080/axon/js/Action.js:225:18)

**Comment by pixelzoom** [comment]
To be considered when a new release branch is created for this sim.  And my feeling is that this is incredibly low priority, and would not block a release.

**Comment by pixelzoom** [comment]
> assigning to responsible dev to determine if it is worth fixing:

I don't think it's worth fixing.  Closing.
